# Only build tags
if: tag IS present
language: python
env:
  global:
    - PY37PATH=/c/Python37:/c/Python37/Scripts
matrix:
  include:
  - os: windows
    language: shell
  - os: linux
    python: 3.6
  - os: osx
    language: generic
before_install:
  - chmod +x install.sh
  - chmod +x test.sh
install:
- travis_wait 40 bash install.sh
script:
- bash test.sh
