[project]
name = "sesam-py"

[tool.black]
line-length = 100
include = '\.py$'

[tool.isort]
line_length = 100
profile = "black"

[tool.pytest.ini_options]
pythonpath = [
  "."
]

[flake8]
# Match black line length
max-line-length = 100
