# This workflow builds and uploads the assets when a new release is created
name: Build release assets
on:
  release:
    types:
      - published
jobs:
  build-and-upload:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        python: [3.7]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Echo information
        run:  |
          echo ${{matrix.os}}
          python --version
      - name: Allow running of install script
        env:
          RUNNER_OS: ${{ matrix.os }}
        run: |
          chmod +x install-gh.sh
      - name: Run install script
        env:
          RUNNER_OS: ${{ matrix.os }}
        run: bash install-gh.sh
      - name: Package assets
        env:
          RUNNER_OS: ${{ matrix.os }}
          TAG: ${{ github.event.release.tag_name }}
        run: bash package-gh.sh
      - name: Upload Windows assets to release
        if: ${{ matrix.os == 'Windows' }}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./dist/sesam-${{ matrix.os }}-${{ github.event.release.tag_name }}.zip
          asset_name: sesam-${{ matrix.os }}-${{ github.event.release.tag_name }}.zip
          asset_content_type: application/zip
      - name: Upload Linux/macOS assets to release
        if: ${{ matrix.os != 'Windows' }}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./dist/sesam-${{ matrix.os }}-${{ github.event.release.tag_name }}.tar.gz
          asset_name: sesam-${{ matrix.os }}-${{ github.event.release.tag_name }}.tar.gz
          asset_content_type: application/tar
