name: Unit Tests

on: 
  pull_request:
    branches: master

jobs:
  run-unit-tests:
    name: Run tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install pytest pytest-md pytest-emoji
          pip install -r requirements.txt

      - name: Move to test dir
        run: cd testing/test_commands

      - uses: pavelzw/pytest-action@v2
        with:
          report-title: 'PyTest Results'
