name: Unit Tests

on: 
  pull_request:
    branches: master
    paths:
      - tests/test_commands

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: pip install pytest pytest-md pytest-emoji
        run: pip install -r requirements.txt
      - uses: pavelzw/pytest-action@v2
        with:
          verbose: true
          emoji: true
          job-summary: true
          click-to-expand: true
          report-title: 'PyTest Results'
